AWSTemplateFormatVersion: "2010-09-09"

Description: 
  "Creating a Launch Template For Jenkins"

Parameters:
  LauchTemplateName:
    Type: String
    Default: 'Jenkins-Launch-Template'
  MyImageID:
    Type: AWS::EC2::Image::Id
  MyInstanceSize:
    Type: String
    Default: t3a.small
  
Resources: 
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
          ImageId: !Ref MyImageID
          InstanceType: !Ref MyInstanceSize
          KeyName: !ImportValue KeyName
      LaunchTemplateName: !Ref LauchTemplateName
